apiVersion: apps/v1
kind: Deployment
metadata: 
  name: tappu-rs
  namespace: default
  labels:
    app: frontend
spec:
  replicas: 5
  selector:
    matchExpressions:
    - key: app
      operator: In
      values:
      - frontend
  strategy:
    rollingUpdate	:
      maxSurge: 25%
      maxUnavailable: 25%
    # type: Recreate
    #matchLabels<map[string]string>   
  template:
    metadata:
      labels:
        app: frontend
      name: pod1
    spec:
      containers:
      - image: nginx
        name: nginx-container
        ports:
        - containerPort: 80
        

